### ISSUE TITLE
Battleforge Gauntlets of Strength - (6595)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1511]
> Something wrong with this item Riveted Gauntlets. When comparing these 2 items its wrongly labeled +15 armor, -4 str, -1 stam. It should be +15 armor, +4 str, -1 stam.

**Comment by Shadownflame** [comment]
This is probably due to the Battleforge item not having fixed stats but rolling them randomly on each drop to provide a different suffix (of the eagle, of the whale etc), and the item comparison tool cannot see the random stats. I have a feeling this problem might be blizzlike but it will need confirmation. Low priority anyhow.

**Comment by Bennylavaa** [comment]
I think this is a bug though some calculation is wrong ill confirm it but put it at cosmetic prio seeing its just cosmetic

**Comment by ghost** [comment]
Blizzlike item compare bug, not an epoch issue
