### ISSUE TITLE
Scepter of Celebras - (17191)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1651]
> Item references Spell Power instead of Spell Damage and Healing increases.

> Still gives spellpower

> The item lists its equip bonus effect as "Increases spell power by 19." as it did in Wrath, when it should list it as "Increases damage and healing done by magical spells and effects by tp to 19.

**Comment by zana244** [comment]
Confirmed on internal, you get the WOTLK reward, which has spell power.
What is more important though, is that you do not get the vanilla version of the scepter that opens up the portal to maraudon.
Rather, the portal is always open and anyone can use it -- basically working like in WoTLK instead of vanilla. Up to devs what they intend to do.
#2140
