### ISSUE TITLE
Mastering the Elements - (8411)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2155]
**In Progress Reports**

> there are two of these quests. i just turned in the fist set. now its asking for a second set?

> This quest felt identical to Elemental Mastery, unsure if it's intended to do this twice

**Comment by Kestrana** [comment]
It looks like there are (Blizzlike) two different breadcrumbs for the shaman ST trinket chain. Both mentioned quests are in Wowhead as step 1 of the chain. While the better player experience would be to remove one quest, this is blizzlike.

**Comment by zana244** [comment]
Indeed, there are two breadcrumbs. However, on internal, if you complete this quest (8411) given by Bath'rah itself you do not get the follow-up Spirit Totem quest. You need to complete the quest from the quest trainer (Elemental Master 8410) in order to access the follow-up quest. Could make them exclusive I guess and also repair the link between Spirit Totem and Mastering the Elements.

Reopening issue.
