### ISSUE TITLE
The Bowyer's Behest - (27775)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2350]
**In Progress Reports**

> Half of the wood piles don't award 1 piece of wood. You loot them and nothing happens. I understand the idea of the quest is to make you run across the plaguelands, but its too punishing (add more nodes please).If it wasn't because track herbs shows the nodes on the minimap (probably bugged) I wouldn't have bothered inishing the quest. Darrowshire doesn't have any node (none got tracked). Andorhal has nodes, but all of them are underground.

> The wood piles on Caer Darrow didn't give wood every time. Sometimes I would interact with them and nothing would happen then they would despawn.

> Logs don't give the item and it seems like they don't respawn
also i've found only 1 location of the logs not sure where to search for more

**Comment by Kestrana** [comment]
There is supposed to be a chance to loot either Simple Wood or the Quest item. The Simple Wood isn't actually dropping and its looking like the wood pile is empty. This could be removed in favor of all of them dropping the wood even though it's not really realistic. I can also add more spawns - the Andorhol ones will need to be moved due to the Andorhol revamp.

**Comment by kaytotes** [comment]
Next deploy.
