### ISSUE TITLE
Volley

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2566]
**Spell ID's:** 1510, 14294

> Auto shot continues while channeling Volley

> Pressing tab interrupt volley

> pushing the button to attack with the pet cancel volley

> Sometimes works for minutes, at least visual effect.

> switching targets causes volley to cancel

**Comment by zana244** [comment]
Uses WotLK behaviour (IIRC) where Auto shot continues while channeling Volley; on vanilla/TBC while you are volleying you cannot auto shoot.

The cancelling from switching targets is, as far as I could tell, due to the auto shot requeuing on the new target and going through with the cast, therefore stopping the volley.

**Comment by ghost** [comment]
Can't mark this for closure with the next update since there's multiple bugs here, so I will state that the next update fixes the auto shot issue, but target switching still breaks volley's channel. So I am going to lower the priority here.
