### ISSUE TITLE
Blind

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2574]
**Spell ID's:** 2094

> Patch 2.3.0 (11/13/2007) blind reagent requirement removed

> Blind must be poison in classc?

**Comment by zana244** [comment]
[Patch 2.3.0] (2007-11-13): Blind is now a physical (no longer a poison) attack. [Reagent] requirement removed. Now shares the same diminish category as Cyclone and is now diminished in [PvE] as well as [PvP].
2.4.3 balance

However, Blind on Epoch still requires Blinding Powder as a reagent, so that could count as a bug.

**Comment by Shadownflame** [comment]
Last I heard some spells were reverted to classic state like reagent costs and needing books to learn or upgrade them. Not sure if this is one of the intentional changes or just an overlook.
EDIT: As per Eredun, this is a custom decision that is still being tuned and the reagent will be made easier to acquire, but it is to stay.

The spell itself is not a poison so that works properly.
