### ISSUE TITLE
Fear

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2616]
**Spell ID's:** 6213

> Fear pathing seems a bit wonky, many times the mobs just run after the player instead of random directions (way too many occasions for it to be random) and sometimes it runs out of "leash range" so it resets while feared and runs back while evading

> Fear occasionally breaks before its duration is over even though no damage have been dealt, only Curse of the Elements has been cast

> mob feared into other pack of mobs not pulling

**Comment by zana244** [comment]
Feared mobs do not pull other mobs if they run close to them, confirmed on internal. -- Same for priest fear, I imagine for warrior fear too.
 Fear pathing does seem wonky somehow, but it's probably not easily fixable due to TC...
 What I managed to reproduce is that if you fear a mob out of combat (not already aggro'ed), they will have an attack animation while being feared and the path *may* be wonkier than usual, but unsure.
 If the mob is aggro'ed onto you from before, he will have the correct scared/fleeing animation while feared.
 
 Could not reproduce fear occasionally breaking, at least in PvE. Maybe in PvP it could be diminishing returns or heartbeat mechanic? (if it is at all implemented on Epoch).

**Comment by Bennylavaa** [comment]
seems fixed.
