### ISSUE TITLE
Mind Flay

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2762]
**Spell ID's:** 17313, 17314, 18807

> After switching talent specialization through dual spec, only Mind Flay rank 1 gets unlearded - ranks 2+ are still in my spellbook and castable

> haven't got the talent, but it's still in my spellbook. Happened after swapping talents with dual spec

> spell still can be use after respec without talent

> After respeccing from shadow to holy I still have Mind Flay and I'm still able to use it

> When you unlearn Mind Flay due to respec, you still keep it as-is

> This spell fkn sucks. It gets resisted by any and everything. A level 38 burning exile in arathi just resisted it

**Comment by zana244** [comment]
No longer remains between specialisations. could not replicate the resist, it seems to work fine?

**Comment by Shadownflame** [comment]
He probably means the fact it runs on binary resist, which is intended on vanilla/bc since it's a snare. Rather than getting some of its damage chipped off by resistances, it either casts or it doesn't, which is adding to the already high miss chance that spells have against higher level targets. In wotlk it was changed to be non-binary along with every other DPS ability, so if someone came from a 3.3.5 server it's a noticeable difference.
