### ISSUE TITLE
Clever Traps

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2784]
**Spell ID's:** 19245

> When I was BM my explosive trap did 94 ticking damage. When I swapped to survival with this talent my ticking damage was 101. If its suppose to be 30% more damage then shouldnt it be ticking roughly 122?

> increased immolation traps damage by exactly 1 damage point per tick. Damage per tick went from 150 to 151

**Comment by zana244** [comment]
Confirmed, it does not properly increase damage for explosive trap / immolation trap.

Works fine for Freezing Trap.

Works well for frost trap, however the animation disappears for 1-2 sec at around 29-30 sec when frost trap would have usually ended, and then the animation reappears for the last 8 seconds which are caused by clever traps.

Think it works fine for snake trap? from 8 to 10?
