### ISSUE TITLE
Sacrifice

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2790]
**Spell ID's:** 19438, 19441

> Casted sacrifice and it "Resisted" XD no shield gained and pet dies

> I cast sacrifice and got the sacrifice bubble without the void walker being sacrificed

**Comment by Shadownflame** [comment]
I can confirm both issues.

1) Sacrifice has the ability to miss and be resisted, none of which should happen. Both mechanics seem to consider the warlock's stats as though it was an enemy to hit (misses have a flat chance against equal level target which is very small 1-2%, resist requires the warlock has Shadow resistance above 0, undead is easiest to test with)

2) This happens when the voidwalker "evades" usually while clipping into a texture. The cast properly applies the shield but fails to kill the voidwalker as it Evades the effect. Related to https://github.com/Project-Epoch/bugtracker/issues/8302

Spell IDs for all ranks 7812, 19438, 19440, 19441, 19443

**Comment by Bennylavaa** [comment]
this seems fixed now will leave for @Shadownflame to test as well. I sac'd about 15 voids no issues
