### ISSUE TITLE
Seal of the Crusader

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2810]
**Spell ID's:** 20307, 21082

> Makes Crusader Strike deal 30% extra damage which is blizzlike, but the lack of information about it on skill's tooltip may confuse players.

> This seal needs to go, it has no place in the game, even with the improved version. This is due to the limited number of debuffs you can apply on a boss, and even if there is no limit, a raid leader would still rather take a better DPS class/spec like a fire mage.

**Comment by T1ti** [comment]
It's 40% and yeah Blizzard never updated the tooltip for it as it was a change in the very last patch of TBC 2.4.2 and they remove it in the wrath pre patch.

> [Patch 2.4.2](2008-05-13): This ability now increases the damage dealt by Spell holy crusaderstrike [[Crusader Strike]] by 40%.

**Comment by ghost** [comment]
The reason it increased the damage dealt by Crusader Strike is because Seal of the Crusader reduces your physical damage done by 40% while it is active, which affected Crusader Strike in TBC. That wasn't fixed until 2.4.2 with that hidden effect. It didn't really need to be clarified because the original interaction didn't make sense either.

That being said, Crusader Strike deals Holy damage here, so during whatever beta this bug report was there was a new bug where Crusader Strike was being buffed by 40% without it also being reduced by 40% as it was no longer physical. That has since been fixed.

So neither of these reports are actually valid bug reports
