### ISSUE TITLE
Demon Portal

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3000]
**Spell ID's:** 93242

> Summon Felguard talent is missing from demonology talent tree

> As someone who's played felguard spec since shortly after TBC came out and played on a TBC pvp server for the last 7 years, I'd prefer to keep the perma-FG tbh. The pet is the one thing that separates Demo from Afflic/Destro as a somewhat unique lock spec. Take away the pet and demo plays like a gimped version of one of the other trees

> Bugged spell that does not work at all, bring back summon felguard

> use a portal icon instead

> Complete shit pls rework

> Portal disappeared after one demon came out. I was on the oil rig in Tanaris.

> unfinished animation i guess? fire totem lol

> Demon portal seems weak, it is awkward to use, minions can die easily. You have to remain close, 3 sec cast time. Demonc acting wierdly. (sometimes, they don't attack immedeitly. (They should be focusing on the warlock target immeadiately)

**Comment by Shadownflame** [comment]
Collection of behavior reports from dupes:

_Demon Portal minions dont have the brain capacity (AI) to go behind their target. They will attack from whichever side of the target you summon them and dont adjust if the target turns or moves. This means if they happen to land in front, about 15% of their attacks are getting parried and there is nothing you can do about it

Demon Portal imp spawns are using some rank1 version of Firebolt which only hits for 30 damage. Max level imp damage should be way higher

lesser voidwalker from demon portal casts disengage instead of whatever the hell he's support to cast to make threat

Warlock talent "Demon Portal" - If demon portal summons a copy of a demon you have already summoned as a pet, your pet stops attacking a mob and runs back,

The Imps and Succubuses are dead when spawning from the new Warlock spell Demon Portal_

**Comment by kaytotes** [comment]
Killed.
