### ISSUE TITLE
hunter pet spamming claw ability not running out of focus

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3057]
> hunter pet spamming claw ability not running out of focus

.go xyz 1057.250000 1391.910000 339.531000 489 0.113985

**Comment by zana244** [comment]
Think this was due to bestial discipline being bugged in the beta and giving double focus... Although, even now it spams claw quite a lot, but it is intended. 25 focus cost, casting every 1.5 sec, and hunter with bestial discipline gets 48 focus every 4 second... almost no downtime, intended. Without talent, pet clearly casts much slower.
