### ISSUE TITLE
Earthbind Totem - (2630)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#314]
> Earthbind slow didn't slow a fleeing mob
`.go xyz -3115.970000 -2235.660000 9.162620 0 5.880280`

**Comment by zana244** [comment]
Could sometimes reproduce on internal...
It seemed as if the slow would not be applied until the NPC decides to switch direction, point at which it updates it speed... Not sure though, and also not sure if specific only to earthbind totem.

**Comment by Shadownflame** [comment]
I cannot reproduce this at all. The only time the totem fails to slow enemies is if the initial "tick" misses, which is fairly common because it's a spell and runs on spell hit table. The totem pulses every 3seconds, so in that case the slow is only applied 3sec later. Naturally, if the mob leaves the totem range in that time frame, it won't slow them at all.
