### ISSUE TITLE
Battlefield Runecloth Bandage is not giving the bandage debuff (...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4004]
> Battlefield Runecloth Bandage is not giving the bandage debuff (you can chain apply them).

.go xyz -7250.850000 -2925.440000 8.827960 1 3.598710

**Comment by Shadownflame** [comment]
Item 19066 runecloth
Item 19067 mageweave
Item 19068 silk
These battlefield bandages have this problem. The wool one applies the Recently Bandaged effect (Spell ID 11196) as intended. 
Unclear if it affects other PvP bandages (they have location requirements in AB and AV which aren't testable on internal)

Furthermore, if you use a bandage which applies Recently Bandaged, and then attempt to use one of the above listed Battlefield bandages, instead of giving the usual error "you can't do that yet" it simply consumes the bandage and shows "immune" as your floating text. This is not correct behaviour either.
