### ISSUE TITLE
Hunter and warlock pet bugs when mounted. When pet gets status e...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4341]
> Hunter and warlock pet bugs when mounted. When pet gets status effect from mobs when mounted, and mob deaggros and leaves, pet will sometimes continue to move at normal walking speed after it catches up to player. This also seems to cause the pet to not regenerate health when not in combat.

.go xyz -8483.730000 -3706.810000 17.552900 1 4.717630

**Comment by Shadownflame** [comment]
Related, but separate issue from: https://github.com/Project-Epoch/bugtracker/issues/7226
I cannot reproduce this however. The pet properly regains follow speed bonus as soon as it leaves combat. Health regens as well. Perhaps @zana244 will have more luck.

**Comment by Bennylavaa** [comment]
I never saw this. 

What happens is while you are in combat the pet just walks slower than the speed when you are not in combat.

@Shadownflame 

To be honest I kind of wish we did pets like on every other classic style server where when mounted they are hidden and don't walk behind you. You can see this type of style by mounting with a pet out and using a teleport npc in a major city after teleport when you are mounted your pet will be hidden and insta summon when you unmount.

**Comment by Shadownflame** [comment]
That's the same thing I suggested, it's the TBC pet implementation. I see too many ways to exploit pets retaining full speed in combat and it wouldn't even be enough to resolve the issue of their follow shenanigans because speed is not the only problem, sometimes they get lost due to pathing and that issue is not getting resolved any soon (improved at most)
