### ISSUE TITLE
sometimes arcane missiles channeling instantly cancels on cast (...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5003]
> sometimes arcane missiles channeling instantly cancels on cast (consumes mana and clear casting proc as well)

.go xyz 261.316000 -3243.620000 113.069000 0 0.679513

**Comment by Shadownflame** [comment]
Happens to other channeled spells too, penance and blizzard mostly. 
Related https://github.com/Project-Epoch/bugtracker/issues/3351

**Comment by ghost** [comment]
This seems to be intended. Arcane Missiles can miss like any other targeted spell, but the spell is flagged to not be logged, and that prevents the "Miss" text from appearing. This flag isn't even used in the core because its purely client side, so possibly a blizzard bug? 

Leaving open anyway because I found a way to fix it and display "Miss", just wanted to clarify on this bug report that this was an Arcane Missiles specific bug. Penance did work the same but Penance has since been removed. Blizzard does not work the same way, but I cannot replicate that one. Mind Flay correctly displays "Miss". I haven't tested Hellfire yet but since that one is a self damaging spell its likely a unique case unrelated to these others.

**Comment by Shadownflame** [comment]
This has been fixed after exploring reasons with Eredun.
