### ISSUE TITLE
Poison cleanse doesn't work if I've been mind controlled by a Hi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5166]
> Poison cleanse doesn't work if I've been mind controlled by a Hive'Regal Slavemaker's mind control poison  because the totem doesn't recognize me as friendly.

.go xyz -7783.810000 508.274000 -41.005800 1 0.424202

**Comment by Shadownflame** [comment]
I'm finding conflicting information regarding how totems behave during MC. The current behavior is that pets and totems don't swap faction when the player is mind controlled, and as far as I remember this is correct. Pets continue fighting your enemy while your character is controlled, and your totems continue working for the party but not yourself, since you are a hostile target for the duration of the MC.

Some players on SOD reported [this ](https://us.forums.blizzard.com/en/wow/t/sod-tremor-totem-does-not-clear-priests-mind-control-in-pvp/1788977/4)on blizz forums as a bug (mentioning their totems become hostile to them while the shaman is mind controlled), which suggest it works the same on blizz and I cannot find any blue posts that would point towards blizz agreeing this is a bug or intending to fix this. 
Other sources, such as [MMO champions from 2010 (wotlk)](https://www.mmo-champion.com/threads/728655-What-breaks-mind-control) suggest that shaman tremor totem is instantly dispelling MC in battlegrounds, which means the totems either swapped faction with the shaman at this point or their pulses worked on the hostile shaman anyway.
I find it possible that the behavior was changed sometime between vanilla and wrath, as I do vaguely remember using Tremor to prevent MC on wotlk.
@Hatson22 do you have any memories what is accurate behavior for tbc 2.4.3?

**Comment by Shadownflame** [comment]
Will remain untouched until someone finds hard evidence of the opposite.
