### ISSUE TITLE
Hi, can Disenchat "Inscribed Gold Ring

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5523]
> Hi, can Disenchat "Inscribed Gold Ring

.go xyz 1664.830000 1683.180000 120.530000 0 4.415350

**Comment by Shadownflame** [comment]
This seems to be the ring from the melee lvl 45 gear crates. Each crate has its own unique ID for the same ring, and neither can be disenchanted despite saying "disenchantable" on mouseover. Kind of strange because every other item from the crates can be. I'm not sure if this needs fixing at all for live, is this ring available from anywhere else in the game? @Bunnyblock2

**Comment by ghost** [comment]
Yes its a normal blizzard item, none of the crate items are supposed to be disenchantable, but the max level crates can be because we couldn't clone them due to the set bonuses, so only the under 55 ones aren't disenchantable.
