### ISSUE TITLE
I dont know if this is a bug.
Mobs dont reset unless there is a ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5602]
> I dont know if this is a bug.
Mobs dont reset unless there is a player in the zone.

.go xyz -8058.930000 -5414.510000 0.589597 1 3.327730

**Comment by Shadownflame** [comment]
This seems to refer to the "mobs don't run back to their spot after you die" issue, it seems they require the presence of somebody being inside the zone to move.
Solo testing in a dungeon, when you die, they properly reset and start running back to their place, but the moment you press release their positions are snapshot while you are outside as a ghost and they do not move until you enter again. Even if you give them like 5 minutes, they will be exactly where you left them (near your corpse, mostly), and continue running back to reset only after you re-enter.

Same thing happens in outside world zones, if you pull a big pack and teleport away, when you teleport back they'll be exactly where you left them and start running back to their spawn spot just then (since there is nobody in any of the zones on Internal)

**Comment by Shadownflame** [comment]
Not fixable as per ktotes, emulator issue.
