### ISSUE TITLE
I am stuck dead after server crash last night. i entered the ins...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6072]
> I am stuck dead after server crash last night. i entered the instance portal to where i died. but i just go inside without reviving.

.go xyz -1450.290000 2617.210000 76.108100 1 6.108650

**Comment by Shadownflame** [comment]
Possibly related https://github.com/Project-Epoch/bugtracker/issues/8292

**Comment by Shadownflame** [comment]
Linking here all the "cant rez in dungeon" stuff. Reported in several different dungeons.

**Comment by Shadownflame** [comment]
While I believe this is indirectly a result of resetting IDs kicking players out of dungeons, this is also an issue of its own because dungeons shouldn't be able to kick out corpses like this. This bug is much wilder than I thought and requires a relog or disconnect following an ID reset to reproduce. You can actually load into the dungeon as a ghost, while your corpse simply gets lost (even disappears from the map).
1) The dungeon resetting after you die is not a problem on its own. You can still rez as long as you haven't logged out, you will just land in a different, fresh ID.
2) Relogging is also not a problem on its own. You can relog as a ghost and re enter and rezz as long as the instance wasn't reset _before_ you relogged (or during). You can even reset the dungeon manually _after_ logging back and it will be okay.
3) This bug specifically happens when the exact sequence of Player Dies/Releases > Dungeon ID resets (manually or via crash, group disband, or expiring ID bug) > Player relogs (Or just logs out and logs back the next morning, but the length of this time frame is unimportant) > Corpse is gone, can't rez in dungeon or anywhere outside.

This is a critical issue that forces players to take rezz sickness for no fault of their own, as their corpse gets lost for good. (This penalty is normally for bad players who can't find where the entrance is)

If for any reason a dungeon does kick out a player's corpse (which, again, shouldn't even happen, unless the player exits the group and gets teleported out as a corpse), it should be teleported to the nearest GY via some failsafe, the same place where the player's ghost spawns. In that case, the player would be able to rezz up from the corpse in the GY without needing to take rezz sickness. The corpse should never ever be lost, and a dungeon should never allow a ghost to load in without resurrecting them.

**Comment by kaytotes** [comment]
Next deploy. Setting to state testing.

**Comment by Shadownflame** [comment]
Corpses no longer get lost.
