### ISSUE TITLE
Hit chance doesnt seem to be correct, im not having any issues h...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6211]
> Hit chance doesnt seem to be correct, im not having any issues hitting a mob 3 levels higher than me even with an offhand equipped. I feel like i should be missing a lot more often

.go xyz -7166.930000 -3804.730000 8.513630 1 5.406520

**Comment by Shadownflame** [comment]
Against + 3 level, when dual wielding in melee you get, without gear, buff, or talents:
27% miss chance 
24% glances
6.5% parry (half of original value by epoch design)
3.25% dodge (half of original value by design)
4-5% critical chance
Rest regular hits (about 35% if attacking from front and 41% from behind since no parries)
This means that about 59-65% of your auto attacks still land, although they don't all do full damage.
Special attacks only have 8% chance to miss as well (this should be 9% on TBC of which only 8% can be offset by hit buffs)
So yeah technically hit is not working correctly , that 1% is missing (from what I can tell, the obligatory 1% is currently added to the spell resist tables and is screwing casters over)
But when leveling, the proportions of your attacks landing is generally correct, all the other numbers check out in game.
