### ISSUE TITLE
Mobs are strange when you are in instances. I don't see casters ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6275]
> Mobs are strange when you are in instances. I don't see casters shooting shadowbolts or frost bolts, and if you jump up on rocks or walls, the mobs will just run into the wall and teleport up to you. Very strange.

.go xyz -7113.340000 -3799.800000 8.370640 1 0.801062

**Comment by Shadownflame** [comment]
Not seeing spells is probably due to this https://github.com/Project-Epoch/bugtracker/issues/6937

The mobs' interaction with walls is however worth investigating. I noticed outside dungeons as well that they're sometimes able to 'jump' after you, it's not really a teleport but they can climb objects they normally shouldn't.
Unsure if it's generic pathing issue https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by Bennylavaa** [comment]
I am going to duplicate and close this, its widely covered by the other two referenced reports.
