### ISSUE TITLE
The duration of mobs running away in fear is too short.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6628]
> The duration of mobs running away in fear is too short.

.go xyz -5049.640000 -290.798000 441.539000 0 0.346193

**Comment by kaytotes** [comment]
This matches TBC damage breaks.

**Comment by T1ti** [comment]
About **Warlock's fear**, idk if this issue is more about mobs fleeing or fear effect.
It still uses the WOTLK formula of breaking when doing 10% of max health
https://github.com/Project-Epoch/TrinityCore/blob/493ee1f7cea7838c841fa870348fc50f293d9f71/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L482


This is the cmangos TBC formula : (It's basically the same as vmangos but does not have the x3 for dots or /3 for players unless it's somewhere else)

```
    uint32 damage = data.damage; Aura* triggeredByAura = data.triggeredByAura;
    // The chance to dispel an aura depends on the damage taken with respect to the casters level.
    uint32 max_dmg = GetLevel() > 8 ? 25 * GetLevel() - 150 : 50;
    float chance = float(damage) / max_dmg * 100.0f;
    if (roll_chance_f(chance))
    {
        RemoveAurasByCasterSpell(triggeredByAura->GetId(), triggeredByAura->GetCasterGuid());
        return SPELL_AURA_PROC_OK;
    } 

```


Here's the vmangos formula : 
```
  uint32 max_dmg = GetLevel() > 8 ? 25 * GetLevel() - 150 : 50;

    if (IsPlayer())
        max_dmg *= 0.333f;

    if (procFlag & PROC_FLAG_TAKE_HARMFUL_PERIODIC)
        max_dmg *= 3;

    float chance = float(originalAmount) / float(max_dmg) * 100.0f;
    if (roll_chance_f(chance))
    {
        triggeredByAura->SetInUse(true);
        RemoveAurasByCasterSpell(triggeredByAura->GetId(), triggeredByAura->GetCasterGuid());
        triggeredByAura->SetInUse(false);
        return SPELL_AURA_PROC_OK;
    }
```


Fear feels like complete shit on epoch still it's constantly breaking on damage.
