### ISSUE TITLE
Priest ability "Power Word: Shield" should stop warrior from get...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6668]
> Priest ability "Power Word: Shield" should stop warrior from getting rage with auto attacks, atleast that's what I recall from Vanilla, but im not 100% sure if it's the same with TBC and Wotlk.

.go xyz -4576.650000 511.171000 56.974900 1 0.456613

**Comment by Shadownflame** [comment]
Got patched sometime around 3.1 iirc. Epoch seems to be using wrath version, which in my opinion is better, but since the baseline is TBC balance, this is up to the devs to decide.

The 3.1 patch change affected both absorb effects on the warrior generating rage from being attacked and absorb effects on his enemy generating rage from his attacks. Reverting this change would result in a negative interaction between priest shield and warrior/bear tanks.

**Comment by ghost** [comment]
We've decided to keep this, so closing as intentional
