### ISSUE TITLE
Created fresh NE warr, it seems that crit chance is jumping arou...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6677]
> Created fresh NE warr, it seems that crit chance is jumping around, initially it was over 11% level 1, now it dropped, 10.04 and another minute its 10.08

Not sure, but ti might be related to thetouch of elune, cause didnt enncounter that on my tauren shaman

.go xyz 10304.700000 885.630000 1332.090000 1 5.781410

**Comment by Shadownflame** [comment]
These values are completely nonsensical, my lvl 1 NE warr started with 10.5%, of which 9.66% is from agility. So the night elf racial is adding 0.84% here instead of 1%. The spell crit is correctly 1%.
The base agi should give 5% crit not 10 to begin with, and it doesn't seem to stack properly with the racial bonus. The latter isn't warrior-specific issue: other classes melee crit also doesn't add up from agility + racial. For example priest is getting 0.86% melee crit from the racial if I deduct the agility component.

**Comment by Shadownflame** [comment]
Warrior crit conversion fixed after ktotes stat rewrite. The 0.04 increment changes are from weapon skill. All works good now.
