### ISSUE TITLE
Vanishing then trying to leave stealth keeps you locked in to "i...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6693]
> Vanishing then trying to leave stealth keeps you locked in to "improved vanish" and stealth until the duration ends

.go xyz 1062.430000 -832.752000 102.762000 0 1.409160

**Comment by Shadownflame** [comment]
Can confirm exiting stealth does not remove the vanish effect and it produces some weird stuff like if you walk on top of an enemy they will strike you once then drop combat. 
Not a high prio issue though as it only happens if you manually unstealth, leaving vanish through attacking something works just fine.
