### ISSUE TITLE
Pets behave weirdly when mounted. Most of the time they will fol...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7226]
> Pets behave weirdly when mounted. Most of the time they will follow, but still respond to combat and thus get lost as you ride on. Not a big problem on a hunter, since resummoning is instant, but really annoying on a warlock.

They should either follow and be immune/passive with regards to combat. Or they should despawn as you mount and respawn as you dismount. Honestly I don't remember what actually used to happen in vanilla, but either of those behaviors would work.

.go xyz 6536.410000 -2670.890000 566.023000 1 4.840190

**Comment by Shadownflame** [comment]
On vanilla the pet would simply follow you while mounted, with pet bar greyed out and stance swapped to "Passive" temporarily. Upon dismounting the pet would immediately swap back to whatever stance you had active earlier. This is very clearly visible here: https://youtu.be/kmRoYJfSwdU?list=PL63DrxiFMWG-hi8ejdnrgvU67P4czp9Ag&t=90
The pet is still susceptible to proximity aggro (which is rare to occur because the owner tends to pick up everything on the road), but will not interact or engage and just continue running after you.

In TBC, due to flying mounts, blizzard changed their behavior to despawn-respawn every time the owner mounts.

It is up to Epoch devs to implement either behavior - since pets are technically on TBC state in other regards and their pathing is far from perfect, I'd vote for the latter option.

Current Epoch behavior is that the pet bar is greyed out but pet remains in defensive/aggressive stance while mounted, which causes them to get side tracked and eventually despawn as the owner keeps moving. Sometimes they also get stuck and despawn due to pathing issues. Related: https://github.com/Project-Epoch/bugtracker/issues/8302
The Water elemental behaves differently. The water elemental doesn't care about player mounting, pet bar remains active, and the pet is still controllable while on a mount. This is also not intended.

**Comment by Shadownflame** [comment]
Defensive pets no longer react to enemies attacking their mounted owner.
Aggressive, however... super glitchy, it keeps attempting to attack the mob but instantly disengages and then attempts again, looks weird, functions weird, pet still falls behind.

**Comment by Shadownflame** [comment]
Seems to function just fine now. Pets are completely passive while mounted, and while they are still susceptible to proximity aggro (the mobs can target them), they will in no way react to any attack and keep following you. They can fall behind if dazed, but otherwise no way to lose them.
Note, this is for permanent pets of warlocks and hunters. The Water Elemental...we don't talk about the Water Elemental.
