### ISSUE TITLE
Died at Razormane Grounds Durotar. Had to run back all the way f...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7243]
> Died at Razormane Grounds Durotar. Had to run back all the way from Orc starting area.

.go xyz -153.415000 -4777.390000 23.658900 1 0.200763

**Comment by zana244** [comment]
#7254

**Comment by Shadownflame** [comment]
This is actually happening if you die in the Captain Flat Tusk area on the far end. It's technically not classified as Razormane Grounds anymore just "durotar", although there are razormane mobs there along with the rare elite, who is highly likely to slay solo aspirants. This area seems to be closer to the Valley of Trials GY from bird view so it ports you there. Same happens if you die anywhere on the Durotar side of the river south of the road. Functionally this is terrible but I'm not sure if it's a bug. Definitely not related to 7254, just a logical failure in GY selection.
![WoWScrnShot_072424_222408](https://github.com/user-attachments/assets/48e80639-aace-4b68-b3dd-cc830148eb81)

**Comment by Shadownflame** [comment]
Note, the logical failure works backwards too, if you die in Burning Blade Coven in the starting area, you get ported to Razor Hill because it is closer in beeline:
![WoWScrnShot_072424_223512](https://github.com/user-attachments/assets/d411c50c-f77e-429d-bfde-3e62e997013e)
I have a hunch this behavior is intended because people on vanilla often used "GY skips" to travel from one zone to another cutting down the walk (you would get ported to the GY physically closer, even if it was on the other side of the mountains)
Leaving it as suggestion for devs if they want to touch this because I don't remember this specific skip existing between Valley and RH.

**Comment by kaytotes** [comment]
Definitely blizzlike it gets the closest graveyard in your zone. It would be a non-trivial amount of work to change this.

**Comment by Shadownflame** [comment]
Ok that settles it.
