### ISSUE TITLE
When mind controlling a mob engaged by a peer (tank) I experienc...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7247]
> When mind controlling a mob engaged by a peer (tank) I experienced a bug after losing control of the mob.  I could not heal or buff my tank ally.  It may have to do with the mind controlled mob having a bleed affect active on it, when I cast the spell.

This issue dissapated about 4 minutes later when I was able to heal and buff the tank companion again.

.go xyz 10311.300000 831.463000 1326.410000 1 2.243640

**Comment by Shadownflame** [comment]
Might be related https://github.com/Project-Epoch/bugtracker/issues/2967

**Comment by Shadownflame** [comment]
Yeah so this happens because of https://github.com/Project-Epoch/bugtracker/issues/8268
The peer continues auto attacking after MC lands until they turn or target something else, which flags them for World Brawler. Then they show up as Invalid Target to healers.
Same bug happens with Enslave Demon.
Note, these bugs flag players for PVP unintended, which can lead to Soul of Iron getting ganked.
