### ISSUE TITLE
I am standing in Burning Blade Coven in the orc/troll starting z...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7254]
> I am standing in Burning Blade Coven in the orc/troll starting zone half way in  I discovered Razormane Grounds which is on the other side completely

.go xyz -30.759900 -4266.430000 66.757200 1 0.571145

**Comment by zana244** [comment]
I wasn't able to confirm this on internal, however if you die inside some parts of the Burning Blade Coven (northern ones), you will spawn as a ghost in Razor Hill instead of Valley of Trials... probably not intended, maybe can find some proof.

Someone mentioned the opposite thing, which I could not confirm either -- Dying in Razormane Grounds and spawning in Valley of Trials as ghost.

Later Edit: It seems dying in the cave to spawn at razor hill is intended.
https://youtu.be/3vlZVAlLfZA?feature=shared&t=395

**Comment by Shadownflame** [comment]
Yeah confirmed this with ktotes in the other thread, blizzlike behaviour that's not gonna be changed.
