### ISSUE TITLE
as a hunter, when in combat, pet doesnt go fullspeed as i am mou...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7266]
> as a hunter, when in combat, pet doesnt go fullspeed as i am mounted

.go xyz -13258.700000 -156.355000 17.110600 0 0.152300

**Comment by Shadownflame** [comment]
This happens if you pull something and get it combat, which is intended. Pets lose their follow speed bonus while in combat.
Out of combat, they properly catch up.

**Comment by zana244** [comment]
That is not intended, if you are mounted your pet should keep the movement speed and follow you passively, even if you pull mobs.
https://www.youtube.com/watch?v=Z6MIJkh3jpQ
1:35 and 2:19:35

I looked at your video on the other issue which was again from Joana, but that is most likely from an old vanilla patch where they did not add the QoL.

Since the pet is inactive, it is really bad behaviour to not make the pet follow you while mounted.

**Comment by Shadownflame** [comment]
Well that's classic behavior vs vanilla. Leave it as a suggestion for devs then to see which version they want. I'm shilling for TBC.

**Comment by Shadownflame** [comment]
New implementation allows pets to retain increased follow speed while the pet themselves is not in combat, even if the owner is. Pets are no longer able to enter combat while the owner is mounted. This fixes the issue of falling behind while mounted.
Pets that are in combat (such as in a pvp situation) will still lose their movement boost.

There is an odd issue with a combat bug happening if the owner manages to mount up while the pet is in combat. The action of mounting immediately teleports the pet back to the owner's side and disengages any enemies, but the combat sticks on the pet and prevents them to regen health. Also gets the owner in combat if they heal or buff the pet. This is however extremely rare and difficult to reproduce and is resolved by killing the mob.
