### ISSUE TITLE
Can't cast Rotten Rations with Water at the same time, maybe a 3...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7315]
> Can't cast Rotten Rations with Water at the same time, maybe a 3.3.5 thing

In vanilla you could macro canibalize with water/food

.go xyz 1873.250000 1589.640000 90.978300 0 3.612410

**Comment by Shadownflame** [comment]
This might be intended since the spell received a redesign to accommodate not needing a corpse to function and the healing component also got nerfed. However I feel it would be nice to keep some of these original traits. This racial was also usable while stealthed in vanilla but here it breaks stealth, it's another thing to consider - other racials such as blood fury do not break stealth.

**Comment by Shadownflame** [comment]
Suggestion rejected by Devs.
