### ISSUE TITLE
Gold and Truesilver should be more rare... Gold seems common in ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7512]
> Gold and Truesilver should be more rare... Gold seems common in the Badlands and Truesilver is EVERYWHERE in badlands and Burning Steppes. If you meant to do that then well done!! :) If not... then it's just too much. I'm not excited to see it... I'm irritated because I'm trying to farm mithril and thorium. Also I haven't seen any dark iron yet and I've farmed A LOT in Burning Steppes and Searing Gorge

.go xyz -6933.210000 -2280.210000 240.744000 0 1.209450

**Comment by Shadownflame** [comment]
This was most likely the impression due to the pooling issues which were just recently fixed. There were just too few of the more common nodes on the beta. Gold and Truesilver aren't meant to be exceedingly rare, there are over 150 blizzlike spawn spots in each zone. 
The Dark iron issue is legit and reported here https://github.com/Project-Epoch/bugtracker/issues/5692
