### ISSUE TITLE
When Carrion VUlture uses Swoop, it will be affected by DR. Afte...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7606]
> When Carrion VUlture uses Swoop, it will be affected by DR. After the third time of getting hit by that skill, it no longer shows up on my debuffs. However, I will still be stunned. It should either show on debuffs or not stun me.

.go xyz 911.615000 -2154.500000 45.846400 0 2.906560

**Comment by Shadownflame** [comment]
Shows up properly to me. Portobello uses the swoop in a rather uncanny way where the 4th swoop is slightly delayed (normally the swoops follow every 14sec after an initial swoop at t=8 after pull), but this one is cast roughly 16sec after the 3rd (about 15sec after it expires, since the duration is like 1sec at this point) so you never get fully immune to the stun, it goes in a cycle of 100% duration, 50% duration, 25% duration, back to 100% - given the time intervals, the DR works fine here, although it's rather strange that the 4th cast is specifically delayed as though on purpose not to trigger the immunity. But the debuff always shows up fine.
Alternatively his spell just runs on a dynamic 14-16sec cooldown and I keep getting unlucky with always resetting DR after 3 swoops.
