### ISSUE TITLE
edit; seal of penitence with widfury totem occasionally causes m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7722]
> edit; seal of penitence with widfury totem occasionally causes me to melee myself

.go xyz 1783.490000 338.219000 -62.313700 0 2.274770

**Comment by Shadownflame** [comment]
This is reproducible. Judgment of Penitence's Windfury procs cause the paladin to melee themselves instead of the enemy. Note, it also flags the paladin with World pvp brawler debuff.
Good question whether Judgment of Penitence should proc WF at all. According to Hatson, only weapon damage mod abilities (i.e. Heroic Strike, Cleave) should do so, and Judgements are not weapon based.

**Comment by Hatson22** [comment]
To clarify; in Vanilla, WF totem used to be able to proc off any melee hit, that included yellow special hits, which is why things like Hamstring spam was meta on Horde side.
In TBC, Windfury Totem was changed to only proc on auto attacks (white hits), or auto attack modifiers/next swing attacks (i.e. Heroic Strike, Cleave), as Shadow posted above. 

Seal of Penitence (aka Seal of Blood) should not be able to proc WF totem, since the attack itself doesn't count as a weapon swing, the general rules are kind of like this for WF totem procs in TBC:
White Attacks (Auto Attacks) - Proc Windfury
Next swing modifiers/attacks that consume auto attack ( Heroic Strike, Cleave etc.) - Proc Windfury
Extra Weapon Attacks (HoJ, Reckoning, Sword Spec, Blinkstrike) - Proc Windfury
Special Attacks (Instant yellow hits that deal damage) - Do not Proc Windfury
Weapon % Extra Damage Attacks (Seal of Righteousness / Seal of Blood, etc) - Do not proc windfury

Bonus clarification on the "extra weapon attacks" examples:
Auto attacks (white hits) also applies to procs that cause extra attacks, such as Hand of Justice, Blinkstrike (TBC weapon), Sword Specialization, etc. Blinkstrike and Sword Spec could even proc themselves in TBC 2.4.3, which Epoch is intending to run class mechanic wise (that's another thing to bug test for Warriors/Rogues btw).
Seal of Command is also scripted as a melee swing, despite being a yellow attack. At least afaik in both Vanilla and TBC, Seal of Command behaves just like a regular extra swing, except that it deals holy damage. But the attack itself can be parried, dodged, blocked, and it can proc other things such as weapon procs, trinkets, other Seals (hence why Seal Twisting was possible).
But we've yet to find concrete proof that SoC could proc WF totem.

**Comment by Shadownflame** [comment]
Judgement of penitence no longer procs windfury. Paladins have stopped slapping themselves.
