### ISSUE TITLE
Spell Detect Greater Invisibility is not available
https://www.w...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7836]
> Spell Detect Greater Invisibility is not available
https://www.wowhead.com/classic/spell=11743/detect-greater-invisibility
pretty usefull in strat/dire maul

.go xyz 1833.220000 -4360.110000 -14.836100 1 4.313110

**Comment by Shadownflame** [comment]
[Patch 2.0.1](https://wowpedia.fandom.com/wiki/Patch_2.0.1) (2006-12-05): Removed.

In terms of TBC balance, we're not supposed to have this. You still have regular Detect Invisibility which serves the same purpose. 
However, dungeon mobs tend to use Greater Invisibility, which is beyond the scope of the regular ability to detect, so devs might want to revisit this matter to keep vanilla dungeons authentic. Either mob invisibility levels need to be adjusted, or this ability should be kept due to the relevance on lvl 60 content. It might be simpler to just give mobs regular Invisibility instead of greater though, considering currently the NPCs in question are either unavailable or not using their Invisibility mechanic, so they'll likely need to be scripted from scratch.

**Comment by ghost** [comment]
Just looked into this and Detect Invisibility was buffed when they removed Detect Greater Invisibility. By a lot too. In Classic Detect Invisibility is 100, while Greater is 300. In TBC Detect Invis is 1000.

You don't really need to know what those numbers mean, just that higher is better, so this is a nonissue
