### ISSUE TITLE
'Searing Blade' rare weapon doesn't proc fireball as far as I ca...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8122]
> 'Searing Blade' rare weapon doesn't proc fireball as far as I can tell

.go xyz -10790.200000 220.171000 30.369000 0 1.745520

**Comment by zana244** [comment]
Confirmed on internal. Saw it proc only once in a few minutes of autoattack + spamming wing clip to fish for procs. Could use a check and a buff.
There might also be an ICD at work, it usually procs at the beginning of the fight? (unsure)

**Comment by Shadownflame** [comment]
Nothing wrong with this weapon, it procs just fine on an adequate level twink. The base proc chance is rather low, this is blizzlike - because it can proc off any hit. So the way to go about it is enchant it with Fiery Weapon and it is best on a paladin who has extra seal attacks too:
![WoWScrnShot_071624_002336](https://github.com/user-attachments/assets/23827caa-e2cf-4fcd-84db-fe084c640502)
Level matters too, iirc on 3.3.5 every proc weapon/effect is suffering a major proc chance loss if you outlevel its original level range. Buffing this weapon any further would potentially put the damage output above Fiery Weapon itself so I advise against. It's just not meant to be that good.
