### ISSUE TITLE
When you fish [in orgrimmar*?] your bobber sometimes becomes unt...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8147]
> When you fish [in orgrimmar*?] your bobber sometimes becomes untargetable and then when you throw your bobber again, the untargetable bobber you threw first doesnt disappear and makes you fail the second bobber you threw

.go xyz 1988.290000 -4649.520000 28.143800 1 3.341060

**Comment by Shadownflame** [comment]
I've seen this bug happen a couple times and it seems to be lag-related. Usually when you miss your fish because of a small lagspike, so you get the message "your fish got away" (or you don't, because you lag through that too), but the bobber is still there in that non-interactable state and if you cast fishing again before the previous times out, it will bug the new cast. Don't even bother trying to reproduce below 200 ms.
Not sure if there is any point putting effort into trying to fix this.
