### ISSUE TITLE
Pets in defensive stance, will not start attacking when the cast...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8212]
> Pets in defensive stance, will not start attacking when the caster is using aoe skills, such as rain of fire

.go xyz 1012.770000 -210.478000 -67.991900 349 1.964040

**Comment by zana244** [comment]
Not sure if they are supposed to? Don't have a lot of knowledge on this as I always play with pet on passive...
On Everlook/Warmane at least, using hunter Volley does not make pet attack the targets, even in defensive stance.

**Comment by Shadownflame** [comment]
Generally speaking, controlled pets do not assist attacks of the owner at all in defensive stance. You need a /petattack macroed to your abilities to have them assist your single target spells too, and using a macro like that with aoe spells when targeting an enemy should work too. (Note there was an assist feature added to the pet bar on cata or mop which is why some people are used to that)
Why I left this thread open for testing is mainly Guardian pets, whom I know had troubles assisting the master on the beta (thinking of demon portal in particular here). As you have no control over these pets, it is important that any attack the player does against an enemy prompts them to attack too.

**Comment by Shadownflame** [comment]
Can confirm guardian pets such as demon portal spawns or druid treants (possibly snake trap..?) aren't engaged by the owner using a ground aoe ability even if it hits the target currently targeted by the owner. 
This is a problem as these pets don't respond to /petattack commands and must naturally assist the owner.
Regular pets don't assist owner attacks regardless of stance so they require no changes.

**Comment by Shadownflame** [comment]
Demon portal scrapped and treants are now controlled pets. This issue is obsolete.
