### ISSUE TITLE
Revenge of Gann quest in the Southern Barrens, they Flying Machi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8214]
> Revenge of Gann quest in the Southern Barrens, they Flying Machine is not spawning on the platform, where it usually does

.go xyz -4029.460000 -2139.950000 93.228900 1 2.831870

**Comment by Bennylavaa** [comment]
It was there on ptr but I bet the issue is the respawn time taking too long maybe? 

13259 (Entry: 3644) - [Bael Modan Flying Machine X:-4173.000000 Y:-2137.149902 Z:84.565002 MapId:1]  
Found nearby gameobjects (distance 10.000000): 1
GUID: GUID Full: 0xf110000e3c0008f8 Type: Gameobject Entry: 3644  Low: 2296
Compatibility Mode: 0
Spawn group: Dynamic Scaling (Quest objectives) (ID: 2, Flags: 9, Active: 1)
Faction: 0 Flags: 4
SpawnID: 13259, location (-4173.000000, -2137.149902, 84.565002)
yaw: 0.628319 pitch: -0.000000 roll: 0.000000
Entry: 3644
Type: 10
Lootid: 0
DisplayID: 330
Name: Bael Modan Flying Machine
Size: 1.000000
AIName:  ScriptName: 
Active AI: class NullGameObjectAI
Model dimensions from center: Max X 2.153722 Y 3.028668 Z 3.735702 Min X -2.716491 Y -2.947799 Z -0.098564

**Comment by Bennylavaa** [comment]
going to confirm it for now but might be intended on the spawn rate. Hard to test with 1 person around.

**Comment by Bennylavaa** [comment]
yep npcs in the area respawn before this and still not respawned after 10 minutes

**Comment by ghost** [comment]
Working correctly on my end. 15m respawn

**Comment by Shadownflame** [comment]
That should really be cut down to 5 min... Is it affected by dynamic respawns?
