### ISSUE TITLE
Mage Portals are not usable when Mage already used it.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8246]
> Mage Portals are not usable when Mage already used it.

.go xyz -8839.060000 666.249000 98.189900 0 3.979340

**Comment by Shadownflame** [comment]
Confirmed issue on beta, however I'll need a partner or an alt account to test exact conditions on the internal realm. 
On most servers this happens when the teleport destination is on a different continent (or zoning out of an instance) and the game no longer registers the mage in your party after they port.

**Comment by Shadownflame** [comment]
Confirmed on internal with Imps, range related issue. To Reproduce this bug you need to make sure you are porting to a different continent or out of a dungeon.

**Comment by kaytotes** [comment]
Retest

**Comment by Shadownflame** [comment]
I can't use the portal at all now (as the mage). Not sure if other people can, yet to do the group test, but this is definitely not okay.

**Comment by kaytotes** [comment]
Retest

**Comment by Shadownflame** [comment]
Seems good now.
