### ISSUE TITLE
mana is not regenerating on "ticks" every 2 seconds as it should...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8274]
> mana is not regenerating on "ticks" every 2 seconds as it should in classic / TBC

.go xyz -859.615000 2524.490000 163.050000 1 1.709770

**Comment by kaytotes** [comment]
Confirmed but arguably not a bug yet, will discuss internally if we even want this.

**Comment by Shadownflame** [comment]
Linking here all the mana regen complaints:
Testing shows that current low lvl mana regen values fall short of even early patch vanilla regen due to the hybridisation of BC values and wotlk continuous regen. This is a massive nerf to mana users during leveling with presumably a slight buff at maximum lvl if the TBC mechanic of Intellect increasing spirit conversion were properly implemented.
Suggestions to either revert completely to the livable 1.12 mechanic or tweak the existing system by increasing the early lvl mp5 are to be considered.

**Comment by Shadownflame** [comment]
Mana regeneration greatly improved. Back to tick regen and values are closer to original vanilla, currently overshooting (higher than blizzlike in some level brackets). In light of inflated stamina/health values across Epoch, this might be functionally the best to keep.

**Comment by Shadownflame** [comment]
As per ktotes, regen values now match vmangos and slight difference from classic is acceptable. Won't receive any further changes.
