### ISSUE TITLE
Greater Earth Elemental (46113) turned into Water

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8363]
![WoWScrnShot_090524_235308](https://github.com/user-attachments/assets/a9b75637-30dd-451e-befe-369b1e9e10df)

**Comment by ghost** [comment]
Decided to drop a comment on this issue because the cause is rather interesting and might come up again later. This was caused by the restoration of NPC models to their vanilla state. The Greater Earth Elemental creature was a reused ID. In 1.12 the ID belonged to an unused mob called Corrupted Water Elemental.

**Comment by Shadownflame** [comment]
Back to his former glory.
