### ISSUE TITLE
Seal of Righteousness Crash

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8375]
Spotted while doing other testing. No crash log. Needs debugging locally.

**Comment by kaytotes** [comment]
No crash log. Can not replicate this in any way. All 3 party members were Paladins. I suspect this is a Paladin issue. Needs consistent test case.

**Comment by Shadownflame** [comment]
I'm not even surprised - the crashes we had weren't consistent and are likely triggered by a specific thing we did. 
What I can share is that the first crash happened very late - we already had two waves of adds on our backs and a third one was underway. Meanwhile the second attempt we crashed before the first wave of adds even spawned (based on the visuals, they were about to spawn). 
My strongest bet is an interaction with the orb itself since on the first test we fully ignored the first two orbs and the adds came out without problems, while on the second test we went straight for the orb. 
I'm not convinced it needs paladins, but it certainly takes 3 people to create a realistic test case.

**Comment by kaytotes** [comment]
I tested with 3 locally for a good while. Do not believe this is archaedas himself.

**Comment by Imperius5k** [comment]
Confirmed crash is caused by SOR

**Comment by Shadownflame** [comment]
Bloody paladins

**Comment by Shadownflame** [comment]
Seal of Righteousness rank 1 no longer hits targets infinite times.
